### ISSUE TITLE
SSL configuration options

### ISSUE THREAD

**Issue by kstaken** [terascope/teraserver#11]
Currently SSL is configured by putting files named a particular way in a directory. This includes the cert signing chain which is assumed to be called gd_bundle-g2-g1.crt. That is only correct for certs issued by one issuer and the code requires it even though not all certs will have one. Each ssl option should probably have a separate configuration parameter and the signing chain should be optional.

**Comment by peterdemartini** [comment]
This issue has migrated to the closed source repo
