### ISSUE TITLE
Add support for DEFLATE

### ISSUE THREAD

**Issue by godber** [terascope/teraserver#20]
Teraserver apps should be able to support HTTP compression.

**Comment by godber** [comment]
Make sure to test the different endpoints:

* Within the API: `http://localhost:8000/api/v1/users?&conditions={}&limit=25&token=APIKEY`
* Within the plugins: `http://localhost:8000/pl/logscope/account/login`

```
curl -I -H 'Accept-Encoding: gzip' "http://localhost:8000/api/v1/users?&limit=25&token=APIKEY
curl -I -H 'Accept-Encoding:gzip' http://localhost:8000/pl/logscope/account/login
```

**Comment by kstaken** [comment]
Added in Pr #21
