### ISSUE TITLE
search module behavior

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraserver#26]
there are inconsistent lucene queries involving urls and any other string that has a ':' in it. Currently you are only able to do a full string search, attempting to do the following does not work q:http\://da* or any kind of variation of it

**Comment by kstaken** [comment]
We need to dig into this again and see if we can find a solution. 

If you query ES directly you can use `field:\"http://da*\"` but going through the search API the escaping doesn't pass through correctly.
