### ISSUE TITLE
Dynamic loading of search endpoints

### ISSUE THREAD

**Issue by kstaken** [terascope/teraserver#29]
We should create a plugin that will dynamically load search endpoints from an ES index.

Currently an endpoint is defined like this:

```
app.use('/api/v1/logstash', function(req, res) {
            var queryConfig = {
                es_client: config.elasticsearch,
                sort_enabled: true,
                sort_default: false,
                sort_dates_only: false,
                date_range: '@timestamp'
            };
            search.luceneQuery(req, res, 'logstash-*', queryConfig);
        });
```

There's no reason that all of that configuration can't be captured in a single document that could be stored in an ES index such that simply posting a new document would be sufficient to create a new search endpoint and therefore avoiding having to deploy updated code to define endpoints.

The configuration document might look something like this.

```
            {
                "endpoint": "/api/v1/logstash",
                "index": "logstash-*",
                "connection": "my-terafoundation-connector-name",
                "sort_enabled": true,
                "sort_default": false,
                "sort_dates_only": false,
                "date_range": "@timestamp"
            }
```

The plugin would then periodically read the index and add or remove endpoints based on the content of the configurations that are deployed.

Note: we would have to be very careful though that if the remote cluster were not available then the currently deployed endpoints should not be touched.

**Comment by jsnoble** [comment]
please check new plugin terascope/teraserver-endpoint , make sure to add teraserver-endpoint to your config file. It checks the index every 10mins by default.

**Comment by jsnoble** [comment]
this is resolved through terascope/teraserver-endpoint
