### ISSUE TITLE
Make it possible for lucene queries to start with wildcards if permitted

### ISSUE THREAD

**Issue by godber** [terascope/teraserver#39]
Right now, `luceneQuery` type queries do not permit leading wildcards.  There are some cases where we want to permit these, but the default should still be disabled.

It should be enabled setting the `leading_wildcard_allowed` option to `true` as shown below:

```
            leading_wildcard_allowed: true
```

**Comment by kstaken** [comment]
Turns out this isn't what was really needed. Closing.
